version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cypress/browsers:node14.16.0-chrome89-ff86
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run ESLint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Publish to Expo
          command: npx expo publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
