version: 2
jobs:
  build:
    macos:
      xcode: "14.0.0"
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-29-node8-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build the app
          command: |
            npm run react-native link
            |
            if [ "$CIRCLE_JOB" = "build-ios" ]; then
              npm run react-native run-ios
            elif [ "$CIRCLE_JOB" = "build-android" ]; then
              npm run react-native run-android
            fi
workflows:
  version: 2
  build:
    jobs:
      - build-ios:
          context: ios
      - build-android:
          context: android
          