version: 2.1
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Start
          command: npm run start
      - run:
          name: Run Web
          command: npm run web
      - run:
          name: Run ESLint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Publish to Expo
          command: npm run publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build