version: 2.1
orbs:
  cypress: cypress-io/cypress@3
jobs:
  build:
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npx expo publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build